### ISSUE TITLE
出现这个是脚本的原因还是网络的原因？测试消息能正常收到

### ISSUE THREAD

**Issue by weiyvshan** [DemoJ/Serv00_SSH#2]
飞书 服务启动
Exception in thread feishu_bot:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/shell/preload/notify.py", line 226, in feishu_bot
    response = requests.post(url, data=json.dumps(data)).json()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)

**Comment by DemoJ** [comment]
这貌似是飞书通知的问题，飞书机器人没有正确给你返回json数据导致异常了，你试试其他推送方式呢。

**Comment by weiyvshan** [comment]
确实是飞书的问题，试了pushplus能够正常推送
